### ISSUE TITLE
Eliminate redundancy in registering resource properties

### ISSUE THREAD

**Issue by joeduffy** [pulumi/pulumi-component-provider-go-boilerplate#2]
It seems there are three places a resource's properties need to be specified:

1. [On the resource struct itself, with `pulumi` tags on its fields](https://github.com/pulumi/pulumi-component-provider-go-boilerplate/blob/7eb316c850edffb18cde189aa2422f59161b2e89/provider/pkg/provider/staticPage.go#L32-L33)
2. [In the call to `RegisterResourceOutputs`, after the resource is created](https://github.com/pulumi/pulumi-component-provider-go-boilerplate/blob/7eb316c850edffb18cde189aa2422f59161b2e89/provider/pkg/provider/staticPage.go#L94-L97)
3. [In the `State` returned from the call to construct the resource](https://github.com/pulumi/pulumi-component-provider-go-boilerplate/blob/7eb316c850edffb18cde189aa2422f59161b2e89/provider/pkg/provider/provider.go#L62-L65)

Is there any reason we can't just use the resource struct as the source of truth, and have ways to get its properties as a `Map` for purposes of the other calls? For example, a `PropertyMap()` function or method on `ResourceState` that uses reflection to look for `pulumi` tags would seem to do the trick. For the example linked to above, it's not too bad, because there are only two properties -- however, I have a Go component that has 20, and I'm finding that it's rather tedious and error prone.

**Comment by mjeffryes** [comment]
closing due to https://github.com/pulumi/pulumi-component-provider-go-boilerplate/issues/34
