### ISSUE TITLE
Switch over to pulumi-go-provider's `infer`

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-component-provider-go-boilerplate#31]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This would prevent user's from needing to hand-author the schema.

**Comment by mjeffryes** [comment]
closing due to https://github.com/pulumi/pulumi-component-provider-go-boilerplate/issues/34
