### ISSUE TITLE
Add integration_tests Makefile target

### ISSUE THREAD

**Issue by jkodroff** [pulumi/pulumi-component-provider-go-boilerplate#9]
Since the process of creating a component provider has a lot of steps in its present form, I think it would be nice to provide users with a end-to-test Makefile target that would create the provider, build the SDKs, and execute all integration tests (examples).  This way, users will be able to get faster feedback if they break something (e.g. by forgetting to update the schema).

**Comment by mjeffryes** [comment]
closing due to https://github.com/pulumi/pulumi-component-provider-go-boilerplate/issues/34
